/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Remark = IDL.Variant({
  'pending' : IDL.Null,
  'received' : IDL.Null,
});
export const RecordData = IDL.Record({
  'mcf' : IDL.Text,
  'remark' : Remark,
  'customerName' : IDL.Text,
  'netAmount' : IDL.Float64,
  'finance' : IDL.Text,
  'loanAmount' : IDL.Opt(IDL.Float64),
  'grossAmount' : IDL.Float64,
  'bankAmountReceivedDate' : IDL.Opt(IDL.Text),
  'brokerageAmountReceivedDate' : IDL.Opt(IDL.Text),
  'serialNumber' : IDL.Nat,
  'product' : IDL.Text,
});

export const idlService = IDL.Service({
  'createRecord' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        Remark,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteRecord' : IDL.Func([IDL.Nat], [], []),
  'getAllRecords' : IDL.Func([], [IDL.Vec(RecordData)], ['query']),
  'getRecord' : IDL.Func([IDL.Nat], [RecordData], ['query']),
  'updateRecord' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        Remark,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Remark = IDL.Variant({ 'pending' : IDL.Null, 'received' : IDL.Null });
  const RecordData = IDL.Record({
    'mcf' : IDL.Text,
    'remark' : Remark,
    'customerName' : IDL.Text,
    'netAmount' : IDL.Float64,
    'finance' : IDL.Text,
    'loanAmount' : IDL.Opt(IDL.Float64),
    'grossAmount' : IDL.Float64,
    'bankAmountReceivedDate' : IDL.Opt(IDL.Text),
    'brokerageAmountReceivedDate' : IDL.Opt(IDL.Text),
    'serialNumber' : IDL.Nat,
    'product' : IDL.Text,
  });
  
  return IDL.Service({
    'createRecord' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          Remark,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteRecord' : IDL.Func([IDL.Nat], [], []),
    'getAllRecords' : IDL.Func([], [IDL.Vec(RecordData)], ['query']),
    'getRecord' : IDL.Func([IDL.Nat], [RecordData], ['query']),
    'updateRecord' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          Remark,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };