/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RecordData {
    mcf: string;
    remark: Remark;
    customerName: string;
    netAmount: number;
    finance: string;
    loanAmount?: number;
    grossAmount: number;
    bankAmountReceivedDate?: string;
    brokerageAmountReceivedDate?: string;
    serialNumber: bigint;
    product: string;
}
export enum Remark {
    pending = "pending",
    received = "received"
}
export interface backendInterface {
    createRecord(finance: string, customerName: string, mcf: string, product: string, grossAmount: number, netAmount: number, loanAmount: number | null, brokerageAmountReceivedDate: string | null, bankAmountReceivedDate: string | null, remark: Remark): Promise<bigint>;
    deleteRecord(serialNumber: bigint): Promise<void>;
    getAllRecords(): Promise<Array<RecordData>>;
    getRecord(serialNumber: bigint): Promise<RecordData>;
    updateRecord(serialNumber: bigint, finance: string, customerName: string, mcf: string, product: string, grossAmount: number, netAmount: number, loanAmount: number | null, brokerageAmountReceivedDate: string | null, bankAmountReceivedDate: string | null, remark: Remark): Promise<void>;
}
import type { RecordData as _RecordData, Remark as _Remark } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createRecord(arg0: string, arg1: string, arg2: string, arg3: string, arg4: number, arg5: number, arg6: number | null, arg7: string | null, arg8: string | null, arg9: Remark): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createRecord(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg8), to_candid_Remark_n3(this._uploadFile, this._downloadFile, arg9));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRecord(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg8), to_candid_Remark_n3(this._uploadFile, this._downloadFile, arg9));
            return result;
        }
    }
    async deleteRecord(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRecord(arg0);
            return result;
        }
    }
    async getAllRecords(): Promise<Array<RecordData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRecords();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRecords();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecord(arg0: bigint): Promise<RecordData> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecord(arg0);
                return from_candid_RecordData_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecord(arg0);
            return from_candid_RecordData_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateRecord(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: number, arg6: number, arg7: number | null, arg8: string | null, arg9: string | null, arg10: Remark): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg9), to_candid_Remark_n3(this._uploadFile, this._downloadFile, arg10));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg9), to_candid_Remark_n3(this._uploadFile, this._downloadFile, arg10));
            return result;
        }
    }
}
function from_candid_RecordData_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecordData): RecordData {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Remark_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Remark): Remark {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mcf: string;
    remark: _Remark;
    customerName: string;
    netAmount: number;
    finance: string;
    loanAmount: [] | [number];
    grossAmount: number;
    bankAmountReceivedDate: [] | [string];
    brokerageAmountReceivedDate: [] | [string];
    serialNumber: bigint;
    product: string;
}): {
    mcf: string;
    remark: Remark;
    customerName: string;
    netAmount: number;
    finance: string;
    loanAmount?: number;
    grossAmount: number;
    bankAmountReceivedDate?: string;
    brokerageAmountReceivedDate?: string;
    serialNumber: bigint;
    product: string;
} {
    return {
        mcf: value.mcf,
        remark: from_candid_Remark_n8(_uploadFile, _downloadFile, value.remark),
        customerName: value.customerName,
        netAmount: value.netAmount,
        finance: value.finance,
        loanAmount: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.loanAmount)),
        grossAmount: value.grossAmount,
        bankAmountReceivedDate: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.bankAmountReceivedDate)),
        brokerageAmountReceivedDate: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.brokerageAmountReceivedDate)),
        serialNumber: value.serialNumber,
        product: value.product
    };
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    received: null;
}): Remark {
    return "pending" in value ? Remark.pending : "received" in value ? Remark.received : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RecordData>): Array<RecordData> {
    return value.map((x)=>from_candid_RecordData_n6(_uploadFile, _downloadFile, x));
}
function to_candid_Remark_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Remark): _Remark {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Remark): {
    pending: null;
} | {
    received: null;
} {
    return value == Remark.pending ? {
        pending: null
    } : value == Remark.received ? {
        received: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
